"""
from io import SEEK_CUR
from tkinter import Radiobutton, Tk     
from tkinter.filedialog import askopenfilename

#       -- Basic GUI --
def get_file():
    Tk().withdraw() 
    filename = askopenfilename()
    return filename


#       -- Create LAMMPS input  --
import os
import os.path
import time
from libsbml import *

#       -- Read SBML file  --
def read_sbml():

    print("\nSelect a SBLM Model")
    filename = get_file()

    print("\nReading SBML file...")
    time.sleep(1)
    document = readSBML(filename)

    #       -- Checks for errors --
    if document.getNumErrors() > 0:
        print("Encountered the following SBML errors:" )
        document.printErrors()
        return 1

    #       -- Get doc version --
    level = document.getLevel()
    version = document.getVersion()
    short_filename = filename[filename.rfind('/')+1:]

    print("\n"  + "File: " + short_filename
                + " (Level " + str(level) + ", version " + str(version) + ")" )
    time.sleep(1)

    model = document.getModel()

    if model is None:
        print("No model present." )
        return 1

    if model.isSetSBOTerm():
        print("      model sboTerm: " + model.getSBOTerm() )
        time.sleep(1)

    return model

def make_lmp(**kwargs):

    r_seed = kwargs.get('r_seed', 5783)
    in_path = kwargs.get('path', 'lammps/in.lmp')

    model = read_sbml()

    if model == 1:
        os._exit(1)

    print("\nCreating lammps file as in.lmp ...")
    time.sleep(1)

    # info
    species = range(1, model.getNumSpecies() + 1)
    reactions = range(1, model.getNumReactions() + 1)
    num_par = model.getNumParameters()

    with open(in_path, 'w') as f:
        f.write('# Agent Based Simulation Of Biological Systems\n\n')
    
        # SET UP OF INPUT VARIABLES
        set_up =[
        "\n#       --- SET UP OF INPUT VARIABLES ---\n",

        "# rnseed : int = seed for random numbers",
        "variable rnseed index 10",
        "variable probability equal random(0,1,${rnseed})\n",

        "# duration : int = N number of steps for the current run",
        "variable time_value index 50  #default value",
        "variable duration equal ${time_value}\n",

        "# atoms : int = N number of atoms of each type to generate ",
        "variable num_atoms index 5",
        "variable atoms equal ${num_atoms}\n"]

        f.writelines(["%s\n" % item  for item in set_up])
    
        # SIMULATION BOX PROPERTIES
        sim_box = [
        "\n#       --- SIMULATION BOX PROPERTIES ---\n",

        "# sym measure units and atoms style",
        "units       lj",
        "atom_style  full \n",

        "# box dimension, boudaries and structure",
        "dimension   3  ",
        "boundary    f f f ",
        "lattice     fcc 3.52\n",

        "# flag2 = on or off for bonded interactions",
        "newton on off\n",

        "# define simulation box",
        "region      box block 0 30 0 30 0 30",
        "create_box  3 box  bond/types 1 extra/bond/per/atom 10\n",

        "# create simulation walls",
        "fix xwalls all wall/reflect xlo EDGE xhi EDGE",
        "fix ywalls all wall/reflect ylo EDGE yhi EDGE",
        "fix zwalls all wall/reflect zlo EDGE zhi EDGE\n"]

        f.writelines(["%s\n" % item  for item in sim_box])

        # AGENTS PROPRETIES AND FORCE FIELDS
        f.write("\n#       --- AGENTS PROPRETIES AND FORCE FIELDS ---\n")
        f.write("# creation of atoms of types in randoms spots inside the box\n")
        
        for i in species:
            f.write("create_atoms" + "    " + str(i) + " random ${atoms} " + str(r_seed) + " box")
            r_seed = r_seed + i
            f.write("\n")

        ag_prop =[
        "\n# atoms mass",
        "mass 1 10.948",
        "mass 2 10.467",
        "mass 3 10.578   # new atoms generated by type 1-2 bond\n",
        
        "# assing atoms to cerian groups",
        "group g1 type 1 ",
        "group g2 type 2",
        "group agents  union g1 g2\n",
        
        "# force fields style and coefficient",
        "pair_style zero 5.0",
        "pair_coeff * *\n",
        
        "# bond style and coefficients",
        "bond_style  harmonic",
        "bond_coeff * 100 1.1\n"]

        f.writelines(["%s\n" % item  for item in ag_prop])
        
        # SIMULATION 
        sim = [
        " \n#      --- SIMULATION ---\n",

        "# set time steps ",
        "timestep 0.01   # seconds\n",
        
        "# This command sets parameters that affect",
        "# the building of pairwise neighbor lists",
        "neighbor 0.001 bin",
        "neigh_modify every 10 delay 100\n",
        
        "# print thermodinamic inf every N timesteps",
        "thermo 100 \n",
        
        "# fix ID group-ID bond/create Nevery itype jtype Rmin bondtype keyword values",
        "# this fix will attempt to create new bond btw atoms of ",
        "# type 1 and 2 every Nevery timestep"]

        f.writelines(["%s\n" % item  for item in sim])

        for i in reactions:
            f.write("fix bond"+str(i)+" all bond/create 10 1 2 1.0 1 prob 0.5 " + str(r_seed))
            r_seed = r_seed + i
            f.write("\n")
        
        sim2 = [
        "\n# set velocity for all atoms",
        "velocity all create 300.0 4928459 rot yes dist gaussian \n",
        
        "# perform plain time integration ",
        "# to update position and velocity",
        "# and simulate Brownioan motion",
        "fix 1 all nve",
        "fix 2 all langevin 300.0 300.0 10.0 904297\n",
        
        "# compute if atoms has a bonds",
        "# and total number of bonds btw all atoms",
        "compute 1 agents property/atom nbonds",
        "compute 2 agents reduce sum c_1 ",           
        "thermo_style custom step temp pe c_2",
        "run 0",
        "# this lines are necessary to insure that the “hasbond” and 'newatoms' ",
        "# variables are current when the group command invokes it.\n",
        
        "# hasbond : boolean = true if atom I has a bond with atom J",
        "variable hasbond atom 'c_1 > 0.0'\n",
        
        "# bondcounter : int = N total number of bonds in the sim",
        "variable bondcounter equal ceil(c_2) \n",
        
        "# print themo info every timestep ",
        "thermo_style custom step temp pe v_bondcounter\n",
        
        "# dumps atoms information ",
        "dump 1 all custom 10 dump.out id x y z type \n"]

        f.writelines(["%s\n" % item  for item in sim2])

        # LOOP 
        loop = [
        "\n#       --- LOOP---\n",
        
        "label loop",
        "variable step loop ${duration}   # loop length\n",
        
        "# create new atoms only if new bonds have been made", 
        "# the num of new atoms is linked to the number of new bonds as follow:",
        "variable newatoms equal floor(${bondcounter}/2)",
        "if '${bondcounter} > 0' then &",
        "'fix depositatoms all deposit ${newatoms} 3 1 5748 region box near 2.0' ",
        "# fix ID group-ID deposit N type M seed keyword values\n",
        
        "# assing all atoms that have a bond to the garbage group",
        "group garbage dynamic all every 1 var hasbond\n",
        
        "# append new values on dump file",
        "dump_modify 1 append yes\n",
        
        "# perform n steps in loop",
        "run 100\n",
    
        "# delate all atoms in garbage",
        "delete_atoms group garbage bond yes mol yes compress no\n",
        
        "# jump to loop lable until step > 0 ",
        "next step",
        "jump SELF loop\n",
        
        "# end of loop",
        "label break\n",
        
        "# check on input variables",
        "variable total_atoms equal ${num_atoms}*2",
        "print ''",
        "print 'Starting Atoms: ${total_atoms}' ",
        "print 'Duration: ${duration}'",
        "print 'ALL DONE' \n"]

        f.writelines(["%s\n" % item  for item in loop])

        f.flush()
        os.fsync(f)
""" 

import os
import os.path

def run_():

    os.system('mkdir -p lammps')

    # default rand seed STARTER -> it will be incremented each time
    r_seed = 5783

    str_in = 'start'
    while True:
        os.system('clear')
        if (str_in == 'start'):
            print("\n   Welcome: \n")
            print("Press 1 to generate a input script\n")
            print("Type q to exit\n")
            str_in = input("> ")
            if (str_in == '1') :
                print("\nThe actual rand seed is: " + str(r_seed) + '\n')
                print("Type a new number if you want to change the rand seed\n")
                print("Press Enter to continue with the default\n")
                n_seed = input("> ")
                if (n_seed != '') : make_lmp(r_seed=int(n_seed), path='lammps/in.lmp')
                else : make_lmp(path='lammps/in.lmp')
                str_in = '0'

        if (str_in != '' and str_in != 'q'):
            os.system('clear')
            print("\n   Action Menu: \n")
            print("Press 1 to look at the lammps script\n")
            print("Press 2 to run the script\n")
            print("Press 3 to restart\n")
            
            print("Type q to exit\n")

        if (str_in != 'q'): str_in = input("> ")

        
        if (str_in == '1') : 
            os.system('less ./LAMMPS/in.lmp')
            str_in = '0'

        elif (str_in == '2') :
            os.system('./run.sh -o dump.out LAMMPS/in.lmp')
            str_in = '0'

        elif (str_in == '3'):
            os.system('python3 main.py')
            return 0
    
        elif (str_in == 'q'):
            print("\nexiting...\n")
            time.sleep(1)
            os.system('clear')
            return 0
        
        elif (str_in == '') : None

        else: print("Error\n")


if __name__ == '__main__':
    run_()
